name: mx_flutter_components
description: A MXMobile SDK
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  mx_crypto_ui:
    path: packages/mx_crypto_ui

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mockito: ^5.2.0

flutter:
  uses-material-design: true
  generate: true
