name: mx_crypto_ui
description: Mx Crypto UI
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mx_crypto_repository:
    path: ../mx_crypto_repository

  mx_share_api:
    path: ../mx_share_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
