name: mx_crypto_ui
description: Mx Crypto UI
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mocktail_image_network: ^0.3.1
  mockingjay: ^0.3.0
  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  mx_crypto_repository:
    path: ../mx_crypto_repository

  mx_share_api:
    path: ../mx_share_api

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

