name: mx_flutter_components

on:
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - "packages/**"
      - ".github/workflows/main.yaml"
      - "pubspec.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2.4.0
        with:
          channel: stable

      - name: "[TEMPORARY] Upgrade Flutter"
        run: flutter upgrade

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random