name: mx_flutter_components

on:
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - "packages/**"
      - ".github/workflows/main.yaml"
      - "pubspec.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: stable

      - name: "[TEMPORARY] Upgrade Flutter"
        run: flutter upgrade

      - name: Install Dependencies
        run: flutter packages get

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1

  unit_test:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Run flutter format
        run: flutter format --dry-run --set-exit-if-changed .
      - run: ./tool/test.sh --coverage
