name: mx_share_api

on:
  pull_request:
    paths:
      - "packages/mx_share_api/**"
      - ".github/workflows/mx_share_api.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/mx_share_api

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.17.5

      - name: Install Dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run tests
        run: dart test --coverage=coverage && pub run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib